angular.module("danse").factory('config', function () {
    return {
        // messages à internationaliser
        msgWaitingInit: "msg_waiting_init",
        msgWaiting: "msg_waiting",
        loadingError: 'loading_error',
        canceledOperation: 'canceled_operation',
        selectMedecin: 'select_medecin',
        identification: 'identification',
        choixMedecinJourTitle: 'choixmedecinjour_title',
        agendaTitre: 'agenda_titre',
        selectClient: 'select_client',
        postRemoveErrors: 'post_remove_errors',
        resaTitre: 'resa_titre',
        chooseAClient: 'choose_a_client',
        postResaErrors: 'post_resa_errors',
        waitingTimeText: 'msg_waiting_time_text',
        listMedecins: 'msg_list_medecins',
        listClients: 'msg_list_clients',
        urlServerLabel: 'msg_urlserver_label',
        loginLabel: 'msg_login_label',
        passwordLabel: 'msg_password_label',
        getMedecinsErrors: 'msg_get_medecins_errors',
        getColoursErrors: 'msg_get_clients_errors',
        agendaTitle: 'agenda_title',
        getAgendaErrors: 'msg_get_agenda_errors',
        getCalendarTitle: 'msg_jour_title',
        // urls du client
        urlLogin: "/login",
        urlHome: "/home",
        urlColour: "/colorManager",
        urlCategory: "/categoryManager",
        urlKind: "/kindManager",
        urlType: "/typeManager",
        urlSize: "/sizeManager",
        urlBox: "/boxManager",
        urlProduct: "/productManager",
        // urls du serveur
        urlSvrColours: "/getAllColours",
        urlSvrCategories: "/getAllCategories",
        urlSvrBoxes: "/getAllBoxes",
        urlSvrKinds: "/getAllKinds",
        urlSvrTypes: "/getAllTypes",
        urlSvrSizes: "/getAllSizes",
        urlSvrProducts: "/getAllProducts",
        urlDeleteColour: "/deleteColour",
        urlDeleteKind: "/deleteKind",
        urlDeleteType: "/deleteType",
        urlDeleteSize: "/deleteSize",
        urlDeleteSizeQuantity: "/deleteSizeQuantity",
        urlDeleteProduct: "/deleteProduct",
        urlDeleteCategory: "/deleteCategory",
        urlDeleteBox: "/deleteBox",
        urlAddOrUpdateProduct: "/addOrUpdateProduct",
        urlAddOrUpdateSizeQuantity: "/addOrUpdateSizeQuantity",
        urlAddOrUpdateColour: "/addOrUpdateColour",
        urlAddOrUpdateCategory: "/addOrUpdateCategory",
        urlAddOrUpdateType: "/addOrUpdateType",
        urlAddOrUpdateKind: "/addOrUpdateKind",
        urlAddOrUpdateSize: "/addOrUpdateSize",
        urlAddOrUpdateBox: "/addOrUpdateBox",
        urlAddOrUpdateProduct: "/addOrUpdateProduct",
        urlAddOrUpdateSizeQuantity: "/addOrUpdateSizeQuantity",
        // délai d'attente maximal pour les appels http en millisecondes
        timeout: 1000,
        // temps d'attente avant une tâche
        waitingTimeBeforeTask: 3000,
        // mode debug
        debug: true,
        // le dictionnaire des locales

    };
});